# my-linux-shell-scripts task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20

inputs:
- name: my-linux-shell-scripts

outputs:
- name: my-linux-shell-scripts-updated

run:
  path: ./my-linux-shell-scripts/ci/scripts/readme-github-pages.sh
  # args: [-debug]
